publish: score parts midi

score: music.ily ../global.ily ../score.ily
	lilypond ../score.ily

parts: music.ily ../global.ily ../parts.ily
	lilypond ../parts.ily

midi: music.ily ../midi.ily
	lilypond ../midi.ily
