publish: score parts midi

score: global.ily music.ily ../score.ly
	lilypond ../score.ly

parts: global.ily music.ily ../parts.ly
	lilypond ../parts.ly

midi: global.ily music.ily ../midi.ly
	lilypond ../midi.ly
